### ISSUE TITLE
mDNS not working

### ISSUE THREAD

**Issue by fynixtech** [adafruit/CC3000_MDNS#4]
Hello, I am using the 1.0.5 IDE and implementing the latest mDNS library for the CC3000, it worked for a few hours but now no matter what I try, mDNS does not work at all. Everything is the same except am at a different location (I dont think this is the problme but who knows). Is there a way to debug this problem and trace the problem. I have no idea what is causing this.

**Comment by q2dg** [comment]
There's something new ?

**Comment by q2dg** [comment]
I see... no

**Comment by ladyada** [comment]
we're deprecating ths library (CC3000 is no longer made/supported)
